# Generated by Django 3.0.8 on 2020-10-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
