# Generated by Django 3.0.8 on 2020-10-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposteria', '0003_auto_20201020_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposteria.PaidOption'),
        ),
    ]
